---
- name: Deploy Scientific Calculator container
  hosts: all
  connection: local
  gather_facts: false
  vars:
    docker_image: "yourname/sci-calc:latest"
    container_name: "sci-calculator"
  tasks:
    - name: Ensure Docker is available
      command: docker --version
      register: docker_check
      changed_when: false
      failed_when: docker_check.rc != 0

    - name: Pull image
      command: docker pull {{ docker_image }}
      register: pull_result
      changed_when: "'Downloaded newer image' in pull_result.stdout"

    - name: Remove existing container (if any)
      command: docker rm -f {{ container_name }}
      ignore_errors: true

    - name: Run calculator container (interactive off; use docker logs -f to view)
      command: >
        docker run -d
        --name {{ container_name }}
        {{ docker_image }}
      register: run_result

    - name: Show running container
      command: docker ps --filter "name={{ container_name }}" --format "{{'{{.ID}} {{.Image}} {{.Status}}'}}"
      changed_when: false

