---
- name: Deploy Scientific Calculator container
  hosts: all
  connection: local
  gather_facts: false

  vars:
    docker_image: "iamruthless/sci-cal:latest"
    container_name: "sci-calculator"

  tasks:
    - name: Ensure Docker is available
      command: docker --version
      register: docker_check
      changed_when: false
      failed_when: docker_check.rc != 0

    - name: Pull image
      command: docker pull {{ docker_image }}
      register: pull_result
      changed_when: "'Downloaded newer image' in pull_result.stdout"

    - name: Remove existing container (if any)
      command: docker rm -f {{ container_name }}
      ignore_errors: true

    # Keep the container running so you can exec into it later
    - name: Run container (keepalive with tail -f /dev/null)
      command: >
        docker run -d
        --name {{ container_name }}
        --entrypoint tail
        {{ docker_image }}
        -f /dev/null
      register: run_result

    - name: Show running container
      command: docker ps --filter "name={{ container_name }}" --format "{{'{{.ID}} {{.Image}} {{.Status}}'}}"
      changed_when: false
      
